name: Build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 18
      - name: Build with Gradle
        run: ./gradlew build --no-daemon --scan            
      -   name: Generate CodeCov Report
          uses: codecov/codecov-action@v3
          with:
              token: ${{ secrets.CODECOV_TOKEN }}

  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 18
      - name: Build with Gradle
        run: ./gradlew.bat build --no-daemon --scan
